<?php

use App\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['name' => 'Afghanistan', 'description' => 'Afghanistan'],
            ['name' => 'Albania', 'description' => 'Albania'],
            ['name' => 'Algeria', 'description' => 'Algeria'],
            ['name' => 'American Samoa', 'description' => 'American Samoa'],
            ['name' => 'Andorra', 'description' => 'Andorra'],
            ['name' => 'Angola', 'description' => 'Angola'],
            ['name' => 'Anguilla', 'description' => 'Anguilla'],
            ['name' => 'Antarctica', 'description' => 'Antarctica'],
            ['name' => 'Antigua and Barbuda', 'description' => 'Antigua and Barbuda'],
            ['name' => 'Argentina', 'description' => 'Argentina'],
            ['name' => 'Armenia', 'description' => 'Armenia'],
            ['name' => 'Aruba', 'description' => 'Aruba'],
            ['name' => 'Australia', 'description' => 'Australia'],
            ['name' => 'Austria', 'description' => 'Austria'],
            ['name' => 'Azerbaijan', 'description' => 'Azerbaijan'],
            ['name' => 'Bahamas', 'description' => 'Bahamas'],
            ['name' => 'Bahrain', 'description' => 'Bahrain'],
            ['name' => 'Bangladesh', 'description' => 'Bangladesh'],
            ['name' => 'Barbados', 'description' => 'Barbados'],
            ['name' => 'Belarus', 'description' => 'Belarus'],
            ['name' => 'Belgium', 'description' => 'Belgium'],
            ['name' => 'Belize', 'description' => 'Belize'],
            ['name' => 'Benin', 'description' => 'Benin'],
            ['name' => 'Bermuda', 'description' => 'Bermuda'],
            ['name' => 'Bhutan', 'description' => 'Bhutan'],
            ['name' => 'Bolivia', 'description' => 'Bolivia'],
            ['name' => 'Bosnia and Herzegovina', 'description' => 'Bosnia and Herzegovina'],
            ['name' => 'Botswana', 'description' => 'Botswana'],
            ['name' => 'Bouvet Island', 'description' => 'Bouvet Island'],
            ['name' => 'Brazil', 'description' => 'Brazil'],
            ['name' => 'British Antarctic Territory', 'description' => 'British Antarctic Territory'],
            ['name' => 'British Indian Ocean Territory', 'description' => 'British Indian Ocean Territory'],
            ['name' => 'British Virgin Islands', 'description' => 'British Virgin Islands'],
            ['name' => 'Brunei', 'description' => 'Brunei'],
            ['name' => 'Bulgaria', 'description' => 'Bulgaria'],
            ['name' => 'Burkina Faso', 'description' => 'Burkina Faso'],
            ['name' => 'Burundi', 'description' => 'Burundi'],
            ['name' => 'Cambodia', 'description' => 'Cambodia'],
            ['name' => 'Cameroon', 'description' => 'Cameroon'],
            ['name' => 'Canada', 'description' => 'Canada'],
            ['name' => 'Canton and Enderbury Islands', 'description' => 'Canton and Enderbury Islands'],
            ['name' => 'Cape Verde', 'description' => 'Cape Verde'],
            ['name' => 'Cayman Islands', 'description' => 'Cayman Islands'],
            ['name' => 'Central African Republic', 'description' => 'Central African Republic'],
            ['name' => 'Chad', 'description' => 'Chad'],
            ['name' => 'Chile', 'description' => 'Chile'],
            ['name' => 'China', 'description' => 'China'],
            ['name' => 'Christmas Island', 'description' => 'Christmas Island'],
            ['name' => 'Cocos [Keeling] Islands', 'description' => 'Cocos [Keeling] Islands'],
            ['name' => 'Colombia', 'description' => 'Colombia'],
            ['name' => 'Comoros', 'description' => 'Comoros'],
            ['name' => 'Congo - Brazzaville', 'description' => 'Congo - Brazzaville'],
            ['name' => 'Congo - Kinshasa', 'description' => 'Congo - Kinshasa'],
            ['name' => 'Cook Islands', 'description' => 'Cook Islands'],
            ['name' => 'Costa Rica', 'description' => 'Costa Rica'],
            ['name' => 'Croatia', 'description' => 'Croatia'],
            ['name' => 'Cuba', 'description' => 'Cuba'],
            ['name' => 'Cyprus', 'description' => 'Cyprus'],
            ['name' => 'Czech Republic', 'description' => 'Czech Republic'],
            ['name' => 'Côte d’Ivoire', 'description' => 'Côte d’Ivoire'],
            ['name' => 'Denmark', 'description' => 'Denmark'],
            ['name' => 'Djibouti', 'description' => 'Djibouti'],
            ['name' => 'Dominica', 'description' => 'Dominica'],
            ['name' => 'Dominican Republic', 'description' => 'Dominican Republic'],
            ['name' => 'Dronning Maud Land', 'description' => 'Dronning Maud Land'],
            ['name' => 'East Germany', 'description' => 'East Germany'],
            ['name' => 'Ecuador', 'description' => 'Ecuador'],
            ['name' => 'Egypt', 'description' => 'Egypt'],
            ['name' => 'El Salvador', 'description' => 'El Salvador'],
            ['name' => 'Equatorial Guinea', 'description' => 'Equatorial Guinea'],
            ['name' => 'Eritrea', 'description' => 'Eritrea'],
            ['name' => 'Estonia', 'description' => 'Estonia'],
            ['name' => 'Ethiopia', 'description' => 'Ethiopia'],
            ['name' => 'Falkland Islands', 'description' => 'Falkland Islands'],
            ['name' => 'Faroe Islands', 'description' => 'Faroe Islands'],
            ['name' => 'Fiji', 'description' => 'Fiji'],
            ['name' => 'Finland', 'description' => 'Finland'],
            ['name' => 'France', 'description' => 'France'],
            ['name' => 'French Guiana', 'description' => 'French Guiana'],
            ['name' => 'ch Polynesia', 'description' => 'French Polynesia'],
            ['name' => 'French Southern Territories', 'description' => 'French Southern Territories'],
            ['name' => 'French Southern and Antarctic Territories', 'description' => 'French Southern and Antarctic Territories'],
            ['name' => 'Gabon', 'description' => 'Gabon'],
            ['name' => 'Gambia', 'description' => 'Gambia'],
            ['name' => 'Georgia', 'description' => 'Georgia'],
            ['name' => 'Germany', 'description' => 'Germany'],
            ['name' => 'Ghana', 'description' => 'Ghana'],
            ['name' => 'Gibraltar', 'description' => 'Gibraltar'],
            ['name' => 'Greece', 'description' => 'Greece'],
            ['name' => 'Greenland', 'description' => 'Greenland'],
            ['name' => 'Grenada', 'description' => 'Grenada'],
            ['name' => 'Guadeloupe', 'description' => 'Guadeloupe'],
            ['name' => 'Guam', 'description' => 'Guam'],
            ['name' => 'Guatemala', 'description' => 'Guatemala'],
            ['name' => 'Guernsey', 'description' => 'Guernsey'],
            ['name' => 'Guinea', 'description' => 'Guinea'],
            ['name' => 'Guinea-Bissau', 'description' => 'Guinea-Bissau'],
            ['name' => 'Guyana', 'description' => 'Guyana'],
            ['name' => 'Haiti', 'description' => 'Haiti'],
            ['name' => 'Heard Island and McDonald Islands', 'description' => 'Heard Island and McDonald Islands'],
            ['name' => 'Honduras', 'description' => 'Honduras'],
            ['name' => 'Hong Kong SAR China', 'description' => 'Hong Kong SAR China'],
            ['name' => 'Hungary', 'description' => 'Hungary'],
            ['name' => 'Iceland', 'description' => 'Iceland'],
            ['name' => 'India', 'description' => 'India'],
            ['name' => 'Indonesia', 'description' => 'Indonesia'],
            ['name' => 'Iran', 'description' => 'Iran'],
            ['name' => 'Iraq', 'description' => 'Iraq'],
            ['name' => 'Ireland', 'description' => 'Ireland'],
            ['name' => 'Isle of Man', 'description' => 'Isle of Man'],
            ['name' => 'Israel', 'description' => 'Israel'],
            ['name' => 'Italy', 'description' => 'Italy'],
            ['name' => 'Jamaica', 'description' => 'Jamaica'],
            ['name' => 'Japan', 'description' => 'Japan'],
            ['name' => 'Jersey', 'description' => 'Jersey'],
            ['name' => 'Johnston Island', 'description' => 'Johnston Island'],
            ['name' => 'Jordan', 'description' => 'Jordan'],
            ['name' => 'Kazakhstan', 'description' => 'Kazakhstan'],
            ['name' => 'Kenya', 'description' => 'Kenya'],
            ['name' => 'Kiribati', 'description' => 'Kiribati'],
            ['name' => 'Kuwait', 'description' => 'Kuwait'],
            ['name' => 'Kyrgyzstan', 'description' => 'Kyrgyzstan'],
            ['name' => 'Laos', 'description' => 'Laos'],
            ['name' => 'Latvia', 'description' => 'Latvia'],
            ['name' => 'Lebanon', 'description' => 'Lebanon'],
            ['name' => 'Lesotho', 'description' => 'Lesotho'],
            ['name' => 'Liberia', 'description' => 'Liberia'],
            ['name' => 'Libya', 'description' => 'Libya'],
            ['name' => 'Liechtenstein', 'description' => 'Liechtenstein'],
            ['name' => 'Lithuania', 'description' => 'Lithuania'],
            ['name' => 'Luxembourg', 'description' => 'Luxembourg'],
            ['name' => 'Macau SAR China', 'description' => 'Macau SAR China'],
            ['name' => 'Macedonia', 'description' => 'Macedonia'],
            ['name' => 'Madagascar', 'description' => 'Madagascar'],
            ['name' => 'Malawi', 'description' => 'Malawi'],
            ['name' => 'Malaysia', 'description' => 'Malaysia'],
            ['name' => 'Maldives', 'description' => 'Maldives'],
            ['name' => 'Mali', 'description' => 'Mali'],
            ['name' => 'Malta', 'description' => 'Malta'],
            ['name' => 'Marshall Islands', 'description' => 'Marshall Islands'],
            ['name' => 'Martinique', 'description' => 'Martinique'],
            ['name' => 'Mauritania', 'description' => 'Mauritania'],
            ['name' => 'Mauritius', 'description' => 'Mauritius'],
            ['name' => 'Mayotte', 'description' => 'Mayotte'],
            ['name' => 'Metropolitan France', 'description' => 'Metropolitan France'],
            ['name' => 'Mexico', 'description' => 'Mexico'],
            ['name' => 'Micronesia', 'description' => 'Micronesia'],
            ['name' => 'Midway Islands', 'description' => 'Midway Islands'],
            ['name' => 'Moldova', 'description' => 'Moldova'],
            ['name' => 'Monaco', 'description' => 'Monaco'],
            ['name' => 'Mongolia', 'description' => 'Mongolia'],
            ['name' => 'Montenegro', 'description' => 'Montenegro'],
            ['name' => 'Montserrat', 'description' => 'Montserrat'],
            ['name' => 'Morocco', 'description' => 'Morocco'],
            ['name' => 'Mozambique', 'description' => 'Mozambique'],
            ['name' => 'Myanmar [Burma]', 'description' => 'Myanmar [Burma]'],
            ['name' => 'Namibia', 'description' => 'Namibia'],
            ['name' => 'Nauru', 'description' => 'Nauru'],
            ['name' => 'Nepal', 'description' => 'Nepal'],
            ['name' => 'Netherlands', 'description' => 'Netherlands'],
            ['name' => 'Netherlands Antilles', 'description' => 'Netherlands Antilles'],
            ['name' => 'Neutral Zone', 'description' => 'Neutral Zone'],
            ['name' => 'New Caledonia', 'description' => 'New Caledonia'],
            ['name' => 'New Zealand', 'description' => 'New Zealand'],
            ['name' => 'Nicaragua', 'description' => 'Nicaragua'],
            ['name' => 'Niger', 'description' => 'Niger'],
            ['name' => 'Nigeria', 'description' => 'Nigeria'],
            ['name' => 'Niue', 'description' => 'Niue'],
            ['name' => 'Norfolk Island', 'description' => 'Norfolk Island'],
            ['name' => 'North Korea', 'description' => 'North Korea'],
            ['name' => 'North Vietnam', 'description' => 'North Vietnam'],
            ['name' => 'Northern Mariana Islands', 'description' => 'Northern Mariana Islands'],
            ['name' => 'Norway', 'description' => 'Norway'],
            ['name' => 'Oman', 'description' => 'Oman'],
            ['name' => 'Pacific Islands Trust Territory', 'description' => 'Pacific Islands Trust Territory'],
            ['name' => 'Pakistan', 'description' => 'Pakistan'],
            ['name' => 'Palau', 'description' => 'Palau'],
            ['name' => 'Palestinian Territories', 'description' => 'Palestinian Territories'],
            ['name' => 'Panama', 'description' => 'Panama'],
            ['name' => 'Panama Canal Zone', 'description' => 'Panama Canal Zone'],
            ['name' => 'Papua New Guinea', 'description' => 'Papua New Guinea'],
            ['name' => 'Paraguay', 'description' => 'Paraguay'],
            ['name' => 'People\'s Democratic Republic of Yemen', 'description' => 'People\'s Democratic Republic of Yemen'],
            ['name' => 'Peru', 'description' => 'Peru'],
            ['name' => 'Philippines', 'description' => 'Philippines'],
            ['name' => 'Pitcairn Islands', 'description' => 'Pitcairn Islands'],
            ['name' => 'Poland', 'description' => 'Poland'],
            ['name' => 'Portugal', 'description' => 'Portugal'],
            ['name' => 'Puerto Rico', 'description' => 'Puerto Rico'],
            ['name' => 'Qatar', 'description' => 'Qatar'],
            ['name' => 'Romania', 'description' => 'Romania'],
            ['name' => 'Russia', 'description' => 'Russia'],
            ['name' => 'Rwanda', 'description' => 'Rwanda'],
            ['name' => 'Réunion', 'description' => 'Réunion'],
            ['name' => 'Saint Barthélemy', 'description' => 'Saint Barthélemy'],
            ['name' => 'Saint Helena', 'description' => 'Saint Helena'],
            ['name' => 'Saint Kitts and Nevis', 'description' => 'Saint Kitts and Nevis'],
            ['name' => 'Saint Lucia', 'description' => 'Saint Lucia'],
            ['name' => 'Saint Martin', 'description' => 'Saint Martin'],
            ['name' => 'Saint Pierre and Miquelon', 'description' => 'Saint Pierre and Miquelon'],
            ['name' => 'Saint Vincent and the Grenadines', 'description' => 'Saint Vincent and the Grenadines'],
            ['name' => 'Samoa', 'description' => 'Samoa'],
            ['name' => 'San Marino', 'description' => 'San Marino'],
            ['name' => 'Saudi Arabia', 'description' => 'Saudi Arabia'],
            ['name' => 'Senegal', 'description' => 'Senegal'],
            ['name' => 'Serbia', 'description' => 'Serbia'],
            ['name' => 'Serbia and Montenegro', 'description' => 'Serbia and Montenegro'],
            ['name' => 'Seychelles', 'description' => 'Seychelles'],
            ['name' => 'Sierra Leone', 'description' => 'Sierra Leone'],
            ['name' => 'Singapore', 'description' => 'Singapore'],
            ['name' => 'Slovakia', 'description' => 'Slovakia'],
            ['name' => 'Slovenia', 'description' => 'Slovenia'],
            ['name' => 'Solomon Islands', 'description' => 'Solomon Islands'],
            ['name' => 'Somalia', 'description' => 'Somalia'],
            ['name' => 'South Africa', 'description' => 'South Africa'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'description' => 'South Georgia and the South Sandwich Islands'],
            ['name' => 'South Korea', 'description' => 'South Korea'],
            ['name' => 'Spain', 'description' => 'Spain'],
            ['name' => 'Sri Lanka', 'description' => 'Sri Lanka'],
            ['name' => 'Sudan', 'description' => 'Sudan'],
            ['name' => 'Suriname', 'description' => 'Suriname'],
            ['name' => 'Svalbard and Jan Mayen', 'description' => 'Svalbard and Jan Mayen'],
            ['name' => 'Swaziland', 'description' => 'Swaziland'],
            ['name' => 'Sweden', 'description' => 'Sweden'],
            ['name' => 'Switzerland', 'description' => 'Switzerland'],
            ['name' => 'Syria', 'description' => 'Syria'],
            ['name' => 'São Tomé and Príncipe', 'description' => 'São Tomé and Príncipe'],
            ['name' => 'Taiwan', 'description' => 'Taiwan'],
            ['name' => 'Tajikistan', 'description' => 'Tajikistan'],
            ['name' => 'Tanzania', 'description' => 'Tanzania'],
            ['name' => 'Thailand', 'description' => 'Thailand'],
            ['name' => 'Timor-Leste', 'description' => 'Timor-Leste'],
            ['name' => 'Togo', 'description' => 'Togo'],
            ['name' => 'Tokelau', 'description' => 'Tokelau'],
            ['name' => 'Tonga', 'description' => 'Tonga'],
            ['name' => 'Trinidad and Tobago', 'description' => 'Trinidad and Tobago'],
            ['name' => 'Tunisia', 'description' => 'Tunisia'],
            ['name' => 'Turkey', 'description' => 'Turkey'],
            ['name' => 'Turkmenistan', 'description' => 'Turkmenistan'],
            ['name' => 'Turks and Caicos Islands', 'description' => 'Turks and Caicos Islands'],
            ['name' => 'Tuvalu', 'description' => 'Tuvalu'],
            ['name' => 'U.S. Minor Outlying Islands', 'description' => 'U.S. Minor Outlying Islands'],
            ['name' => 'U.S. Miscellaneous Pacific Islands', 'description' => 'U.S. Miscellaneous Pacific Islands'],
            ['name' => 'U.S. Virgin Islands', 'description' => 'U.S. Virgin Islands'],
            ['name' => 'Uganda', 'description' => 'Uganda'],
            ['name' => 'Ukraine', 'description' => 'Ukraine'],
            ['name' => 'Union of Soviet Socialist Republics', 'description' => 'Union of Soviet Socialist Republics'],
            ['name' => 'United Arab Emirates', 'description' => 'United Arab Emirates'],
            ['name' => 'United Kingdom', 'description' => 'United Kingdom'],
            ['name' => 'United States', 'description' => 'United States'],
            ['name' => 'Unknown or Invalid Region', 'description' => 'Unknown or Invalid Region'],
            ['name' => 'Uruguay', 'description' => 'Uruguay'],
            ['name' => 'Uzbekistan', 'description' => 'Uzbekistan'],
            ['name' => 'Vanuatu', 'description' => 'Vanuatu'],
            ['name' => 'Vatican City', 'description' => 'Vatican City'],
            ['name' => 'Venezuela', 'description' => 'Venezuela'],
            ['name' => 'Vietnam', 'description' => 'Vietnam'],
            ['name' => 'Wake Island', 'description' => 'Wake Island'],
            ['name' => 'Wallis and Futuna', 'description' => 'Wallis and Futuna'],
            ['name' => 'Western Sahara', 'description' => 'Western Sahara'],
            ['name' => 'Yemen', 'description' => 'Yemen'],
            ['name' => 'Zambia', 'description' => 'Zambia'],
            ['name' => 'Zimbabwe', 'description' => 'Zimbabwe']
        ];
        foreach($data as $item){
            Country::create($item);
        }
    }
}
